### ISSUE TITLE
Error in retrieving data

### ISSUE THREAD

**Issue by kanchan04katare** [RedHatInsights/insights-frontend#108]
Go to insights rules tab
From stability tab click on 'permanently ignore rule'.
Observe

Error retrieving data error is observe in UI.
<img width="1280" alt="error_retriving_data" src="https://cloud.githubusercontent.com/assets/7577468/26715340/fba0e22c-4792-11e7-8c64-a49f80cb932a.png">

@iphands

**Comment by iphands** [comment]
@kanchan04katare 

Works for me, can you repeat it?

**Comment by iphands** [comment]
Also I we don't throw 504 status codes from the API.
I think this is a networking error between you and Insights API. Closing unless we can have some repeatable issue to tackle.
