### ISSUE TITLE
Satellite systems visible with "showSatellite" option disabled

### ISSUE THREAD

**Issue by lphiri** [RedHatInsights/insights-frontend#111]

**Comment by iphands** [comment]
@lphiri is there an easy repro for this? I'd like to move this to the API issues list, but I'll leave it here for now because we are in the process of moving the repo.

**Comment by lphiri** [comment]
@iphands  I think we determined this was an internal account only issue/design intent - danK can confirm

**Comment by dkuc** [comment]
As far as I'm aware this is working as intended.
