### ISSUE TITLE
Planner - system missing from add specific system search results

### ISSUE THREAD

**Issue by Robcwilliams** [RedHatInsights/insights-frontend#114]
On the default RH account there is a system registered in inventory as "ceeph.jaylin". When typing in "jaylin" in the filter, no matching result appears.

Steps to Reproduce:
1. Open https://access.redhat.com/insightsbeta/planner/
2. Click "Create a plan"
3. Click "Specific System"
4. Input a key word to filter the system you want to select

https://bugzilla.redhat.com/show_bug.cgi?id=1459761

**Comment by jharting** [comment]
@Robcwilliams good catch!
