### ISSUE TITLE
Incidents integration issues

### ISSUE THREAD

**Issue by mattnolting** [RedHatInsights/insights-frontend#117]
Actions widget 'Incident summary'
- The link 'View incidents' needs to work

Filters on a severity 
- If user clicks into a severity, the filters should be set when they arrive at that view. 
- 'Topic details' don't reflect the appropriate severity when updated.
- If user is viewing issues with a severity selected and selects another severity from the filters, then the page topic-details should update. (Topic detail section isn't very helpful/needed when viewing a severity; will likely be removed)
- **'Clear all filters'** link should appear when at least two filter selections have been made.

**Comment by Kinlaw** [comment]
Fixed with https://github.com/RedHatInsights/insights-frontend/commit/415085338674e7aecdcb5d44dde8201d4469654f

**Comment by mattnolting** [comment]
- Incident widget on Actions landing page loads differently than the other widgets. There's enough lag that it could be missed 
- Toolbar search pattern needs to be on the third view as well replacing 'actions-rule-filter.'

**Comment by mattnolting** [comment]
Incident filter
- Deleting the 'Incident' radio selection by using the delete button doesn't reset the radio buttons

**Comment by Kinlaw** [comment]
Fixed
- 'Incident' radio fixed.
- Synced all components on actions landing page

Pushing to next iteration
- Toolbar search pattern on actions page 3
I'm planning to work on refactoring all Insights searches/filters to use the collapsableFilter component once this MR is merged.

**Comment by Kinlaw** [comment]
Closing since all of the noted issues are fixed.
