### ISSUE TITLE
side margins missing in certain places

### ISSUE THREAD

**Issue by jharting** [RedHatInsights/insights-frontend#119]
![04](https://user-images.githubusercontent.com/167352/26972202-061b5e20-4d11-11e7-828b-a7ffa82fba7c.png)
![05](https://user-images.githubusercontent.com/167352/26972203-0639ee12-4d11-11e7-8143-5f89f6dab5e9.png)

**Comment by iphands** [comment]
@jharting is there some trick we can use to get to the entitlements page?
The second image is https://access.redhat.com/insightsbeta/announcements/

**Comment by jharting** [comment]
@iphands I wish I remembered. I think you need to run frontend + api locally and modify devauth to give you some other account than 540155

**Comment by iphands** [comment]
@jharting thanks that helps. @ryelo lemme know if you need help getting to that page.

**Comment by iphands** [comment]
On hold until until headers from collapsible-filters gets merged.
