### ISSUE TITLE
The knowledgebase link is grey on white, and out of place looking.

### ISSUE THREAD

**Issue by iphands** [RedHatInsights/insights-frontend#133]
![tmp](https://user-images.githubusercontent.com/129737/27433833-4ed754f8-5724-11e7-8ceb-e2b14ca34da9.jpg)

**Comment by ryelo** [comment]
The div has a 'gray top' class on it. I could make a 'transparent top' class with the same styles as the gray top, but without the background-color. Otherwise, there are some alignment issues if you just take 'gray' out of it completely.

**Comment by iphands** [comment]
Yeah I think either ungray, or move into the gray space. Or re think
entirely. There is no right answer here, but there are probably a few wrong
answers.

On Jun 27, 2017 11:25 AM, "Ryan Long" <notifications@github.com> wrote:

The div has a 'gray top' class on it. I could make a 'transparent top'
class with the same styles as the gray top, but without the
background-color. Otherwise, there are some alignment issues if you just
take 'gray' out of it completely.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/RedHatInsights/insights-frontend/issues/133#issuecomment-311393607>,
or mute the thread

**Comment by iphands** [comment]
This was fixed by @ryelo
