### ISSUE TITLE
On Actions page 2 (click on a category) "View Impacted Systems" is out of place

### ISSUE THREAD

**Issue by iphands** [RedHatInsights/insights-frontend#135]
![tmp](https://user-images.githubusercontent.com/129737/27434040-35fbc09e-5725-11e7-84e3-e586461c069f.jpg)

**Comment by mattnolting** [comment]
It's consistent with Rules and Topic Cards.. If the request is to redesign the list view, we'll need to scope.

**Comment by iphands** [comment]
You are right, it is consistent, but it doesn't look fugly to yah?
It just looks way higher up on the y axis than it should to me.

![tmp](https://user-images.githubusercontent.com/129737/27453162-81424d96-5763-11e7-9006-406be71810ff.jpg)
