### ISSUE TITLE
Actions Page 3... Incidents icon is out of position

### ISSUE THREAD

**Issue by iphands** [RedHatInsights/insights-frontend#136]
![tmp](https://user-images.githubusercontent.com/129737/27434073-5d019d44-5725-11e7-8ad1-5c6a17c4d4c1.jpg)

**Comment by mattnolting** [comment]
Padding updated for h1 - h6

**Comment by iphands** [comment]
The zindex fixe works and the total height of the groups flyout is now reduced due to a scroll bar.
Looks like this is doubly fixed... merging. Thanks @mattnolting

**Comment by iphands** [comment]
> Padding updated for h1 - h6 

@mattnolting Hey, where did ya fix it? Forget the MR?

**Comment by Kinlaw** [comment]
Fixed by #147
