### ISSUE TITLE
Make non global filters appear in a consistent place

### ISSUE THREAD

**Issue by iphands** [RedHatInsights/insights-frontend#137]
ATM the filters are above the content and thus they are not found in a uniform place while drilling down (and could not be uniform when switching from Actions to Inventory).

The mock up had the non global filters in a drop down sort of thing that was consistent while drilling down and while moving from section to section: https://drive.google.com/drive/u/1/folders/0B0JNmw3aowwpSWFfSUhxNWgxcnM

The filter options available in the dropdown should/can change as you move about, but its location (the "tray" the filters live in) should remain the same.

**Comment by iphands** [comment]
Bonus points if pressing the tilda/grave key makes the filters rollup/rollout. Like Tilda, Guake, Yakuake.

**Comment by Kinlaw** [comment]
Fixed in https://github.com/RedHatInsights/insights-frontend/pull/173.

Going to add tilda/grave key on next push.

**Comment by Kinlaw** [comment]
Closing since the dropdown filter is no longer in the app.
