### ISSUE TITLE
RFE: Quick filter for groups selection

### ISSUE THREAD

**Issue by iphands** [RedHatInsights/insights-frontend#138]
Add a text filter to the groups dropdown list

![tmp](https://user-images.githubusercontent.com/129737/27434620-517dfb6e-5727-11e7-89ba-d237f8a2cea5.jpg)

**Comment by mattnolting** [comment]
@ryelo is going to wireframe the interaction

**Comment by ryelo** [comment]
[InteractionWireframe.pdf](https://github.com/RedHatInsights/insights-frontend/files/1097937/QuickFilterWireframe-4.pdf)

**Comment by iphands** [comment]
Wireframe looks great lets build it!

**Comment by Kinlaw** [comment]
Merged into master. Closing
