### ISSUE TITLE
Put incidents somewhere on /overview

### ISSUE THREAD

**Issue by iphands** [RedHatInsights/insights-frontend#139]
Something lighter than the full blown Incidents UI should appear on the Overview page.

**Comment by iphands** [comment]
@Kinlaw @mattnolting @ryelo 

This (below) already exists on the `Actions` landing page.
Should we take it in full over to `Overview`? Or should we make a much smaller *lite* widget for `Overview`?

![tmp2](https://user-images.githubusercontent.com/129737/30550409-613805d0-9c65-11e7-9eb0-0b2489ad1706.png)

**Comment by iphands** [comment]
@Kinlaw @mattnolting @ryelo 

This (below) already exists on the `Actions` landing page.
Should we take it in full over to `Overview`? Or should we make a much smaller *lite* widget for `Overview`?

![tmp2](https://user-images.githubusercontent.com/129737/30550409-613805d0-9c65-11e7-9eb0-0b2489ad1706.png)

**Comment by mattnolting** [comment]
@iphands I like the idea of creating a lite version and adding the supporting text as a note or tooltip..
