### ISSUE TITLE
Change no issues of severity check to green

### ISSUE THREAD

**Issue by Robcwilliams** [RedHatInsights/insights-frontend#143]
This came up during a discussion with Andrew while walking through the UI. He mentioned he expected to see the check symbol which shows up when there's no issues of a severity identified to be green (similar to what we do on exec reports with resolved issues text)

<img width="324" alt="screen shot 2017-06-27 at 2 12 42 pm" src="https://user-images.githubusercontent.com/343792/27603012-b5b6178c-5b42-11e7-9a43-d7c81932c769.png">

**Exec Report style (example with green)**
<img width="410" alt="screen shot 2017-06-27 at 2 15 05 pm" src="https://user-images.githubusercontent.com/343792/27603094-0b7c21de-5b43-11e7-8b4f-127e545e37a9.png">

**Comment by iphands** [comment]
Easy peasy. @mattnolting your thoughts though?

**Comment by mattnolting** [comment]
Ship it!

**Comment by iphands** [comment]
Lol it's an issue not yet a PR
