### ISSUE TITLE
Rules page takes way too long to load

### ISSUE THREAD

**Issue by Kinlaw** [RedHatInsights/insights-frontend#153]
Loading up the rules page on insightsbeta is taking 8-10 seconds to fully load. Even after all of the network calls finish, it's still taking an additional 3 seconds or so to replace the loading spinner with the rules content.

**Comment by iphands** [comment]
@Kinlaw is it doing a bunch of CPU processing the response to build the UI?

**Comment by Kinlaw** [comment]
@iphands I think it's half and half. We are query and returning all of the rules at once which is taking 3 - 4 seconds. The UI then takes another 2 - 4 seconds to process/render everything.
