### ISSUE TITLE
Planner modal shows inaccurate count of systems for selected group

### ISSUE THREAD

**Issue by Kinlaw** [RedHatInsights/insights-frontend#169]
If I create a new plan and select the jkinlaw system group, I am shown that I have 2 systems in this group but this group actually has 140 systems.

![screen shot 2017-07-13 at 9 48 55 am](https://user-images.githubusercontent.com/5181010/28169641-fd793502-67b0-11e7-946d-1a4cd1f1229d.png)

**Comment by jharting** [comment]
I've noticed this also. Fixed here: https://github.com/RedHatInsights/insights-frontend/pull/164/commits/e48392dd42cd012b967a8cee48bd9e4cd858b99e part of https://github.com/RedHatInsights/insights-frontend/pull/164
