### ISSUE TITLE
System modal below Portal header, and slightly offset to the left

### ISSUE THREAD

**Issue by iphands** [RedHatInsights/insights-frontend#171]
![tmp](https://user-images.githubusercontent.com/129737/28172146-c74143c8-67b8-11e7-8a68-f2f26c0fc663.jpg)

**Comment by jharting** [comment]
FYI I think it affects all modals, not just system modal

**Comment by Kinlaw** [comment]
I noticed this as well. It affects the create playbook modal and the initial selection of options when resolving a rule with multiple plans, but not when editing an option from the Playbook Summary tab.
![screen shot 2017-07-13 at 12 08 53 pm](https://user-images.githubusercontent.com/5181010/28176067-0e65ffea-67c4-11e7-9818-d50f9cc4da00.png)
![screen shot 2017-07-13 at 12 10 20 pm](https://user-images.githubusercontent.com/5181010/28176118-405ec0ae-67c4-11e7-9cc6-f79d86d0f18f.png)
