### ISSUE TITLE
Change inventory infinite scroll to pagination

### ISSUE THREAD

**Issue by Robcwilliams** [RedHatInsights/insights-frontend#175]
Background
This has been discussed internally by FMS having the inventory going to pagination rather than infinite scroll. Infinite scroll has made some less than ideal experiences for users as they begin to scale out to larger deployment sizes. Additionally, bottom buttons like export CSV or whatever else we decide to use that real estate for are constantly pushed down and inaccessible until the user gets to the last result. 

Story
As a user I can use pagination to navigate thru my inventory. Filtering should affect all my results, not just the current page.

**Comment by Kinlaw** [comment]
Merged into master via #199
