### ISSUE TITLE
Evaluation page could use some visual TLC

### ISSUE THREAD

**Issue by Robcwilliams** [RedHatInsights/insights-frontend#179]
This is one of the first interactions new potential customers have experience with Insights.

No changes to the evaluation logic itself, just the visual presentation of the page.
access.redhat.com/insights/evaluation

**Comment by ryelo** [comment]
![screen shot 2017-08-01 at 10 06 14 am](https://user-images.githubusercontent.com/12520842/28829291-3f0df0a8-76a1-11e7-8c6c-3a60bce92c8c.png)

This Error screen is the only one that still has work to be done. It functions for now, but I'm going to implement a try again button for different error states. On hold until Dan gets back.

![screen shot 2017-08-01 at 10 06 22 am](https://user-images.githubusercontent.com/12520842/28829292-3f0ec2b2-76a1-11e7-8927-1cef929ba476.png)
![screen shot 2017-08-01 at 10 06 30 am](https://user-images.githubusercontent.com/12520842/28829294-3f0f4d0e-76a1-11e7-87a1-5077150ca3b2.png)
![screen shot 2017-08-01 at 10 06 37 am](https://user-images.githubusercontent.com/12520842/28829293-3f0f31b6-76a1-11e7-8a6d-b38c36f0ab40.png)
![screen shot 2017-08-01 at 10 06 44 am](https://user-images.githubusercontent.com/12520842/28829295-3f1d832e-76a1-11e7-9ee2-66d8d99cb2a5.png)
