### ISSUE TITLE
UX Mockups - Risk of change 

### ISSUE THREAD

**Issue by Robcwilliams** [RedHatInsights/insights-frontend#189]
High level mockups for UI implementation of Risk of change

https://docs.google.com/document/u/1/d/1M-yjsg3zYpkTUQP2dtESPV6gwm9GOswCdXusQuIGWp8/edit?usp=drive_web

**Comment by Robcwilliams** [comment]
https://drive.google.com/a/redhat.com/file/d/0Bxu2vT9Mq-FBMGJPd3d1SUUwdnM/view?usp=sharing

**Comment by jharting** [comment]
http://labs-git.usersys.redhat.com/labs/telemetryapi/merge_requests/426
