### ISSUE TITLE
Inventory actions always disabled

### ISSUE THREAD

**Issue by jharting** [RedHatInsights/insights-frontend#191]
![01](https://user-images.githubusercontent.com/167352/28610938-7454b4d8-71ea-11e7-8c1b-6def61265105.png)

Looks like this regression was introduced in https://github.com/RedHatInsights/insights-frontend/commit/ef682a3b9d58fcae6f86960c1a9f41f7327e8e8b

**Comment by jharting** [comment]
@Kinlaw Looks like this happens because `inventory-actions` is no longer used by `inventory.jade` (and therefore functions provided by its controller are no longer available)

**Comment by Kinlaw** [comment]
In progress.
