### ISSUE TITLE
Additional search guidance on search boxes [BZ 1427581]

### ISSUE THREAD

**Issue by Robcwilliams** [RedHatInsights/insights-frontend#202]
From the BZ (Please see BZ for additional information - customer specific details have been removed):
> There are several search boxes in the Insights WebUI, a customer has no idea about the function (search globally / search in the specific list). Some info button with hover information will be helpful.

Looks like this is just for **Planner** and **Rules** as both just have "Search...". Inventory uses "Find a system".

**Comment by jharting** [comment]
Fixed in https://github.com/RedHatInsights/insights-frontend/pull/207
