### ISSUE TITLE
No obvious way to switch back to insights stable after switching to beta

### ISSUE THREAD

**Issue by Kinlaw** [RedHatInsights/insights-frontend#234]
As a user if I go to Insights and then select "Try Insights Beta", I am taken to Insights beta. From here, I have the option to Default to Beta but I have no obvious way to get back to stable. If I hit the back button in my browser I am taken to the evaluation page. If I hit the back button again, I am taken to Insights Beta again. If I hit the back button one more time, I am taken to Insights Stable. 

I feel like I should be taken to Insights Stable after selecting the back button the first time but definitely after hitting it the second time.

**Comment by ryelo** [comment]
I'll work on the flow for this and then get it implemented into unportal

**Comment by ryelo** [comment]
Got the functionality working in unportal. Waiting for that to be pushed.
