### ISSUE TITLE
Score variance shows incorrect increase when score changes from 0 to a valid score.

### ISSUE THREAD

**Issue by Kinlaw** [RedHatInsights/insights-frontend#243]
Account 6 has a dip where it looks like all of the systems were unregistered and then reregistered. As a result the score variance shows that the score has improved by 487 when it should actually be 487 - 250 since 250 is the lowest the score could be.

![screen shot 2017-09-28 at 3 20 45 pm](https://user-images.githubusercontent.com/5181010/30986213-a5b2d188-a460-11e7-9682-7ac866112c2d.png)

**Comment by Kinlaw** [comment]
Still an issue
<img width="708" alt="screen shot 2018-03-01 at 9 11 00 am" src="https://user-images.githubusercontent.com/5181010/36848888-980460da-1d30-11e8-8933-628dd421fa98.png">

**Comment by Kinlaw** [comment]
<img width="708" alt="screen shot 2018-03-01 at 9 11 00 am" src="https://user-images.githubusercontent.com/5181010/36861781-ead9ba04-1d52-11e8-888b-e6445ffdeeae.png">

**Comment by Kinlaw** [comment]
Fixed! If this gets reviewed after today you can test this change by changing line 214 to use a digestBase.score that is 0.

![screen shot 2018-03-01 at 1 17 21 pm](https://user-images.githubusercontent.com/5181010/36861806-fd34faa6-1d52-11e8-885d-5c6ce8fdcb33.png)

**Comment by jharting** [comment]
@Kinlaw has this been reported to @jhjaggars ? Looks like we should never be returning 0 score for digests.
