### ISSUE TITLE
Planner auto selects a group for default view vs select all

### ISSUE THREAD

**Issue by Robcwilliams** [RedHatInsights/insights-frontend#246]
When creating a plan, the default view which is shown is that of a group which seems to be automatically selected. There is no global filter in place during this and the results which are shown are limited because it's only showing those of a group. To view all my results as options to create a plan - I need to go and select "All Systems" but this should be the default view. 

Ideal situation would be when creating a plan, by default use the all systems view - then I can use subset views if decide to use those. 

Steps to replicate:
1. Go to Insights (Beta) & confirm no global filter selected
2. Select planner

<img width="935" alt="screen shot 2017-10-02 at 7 07 19 pm" src="https://user-images.githubusercontent.com/343792/31103548-7c17b1f2-a7a5-11e7-9609-0cb878eafa25.png">

**Comment by jharting** [comment]
Implemented in https://github.com/RedHatInsights/insights-frontend/pull/283
