### ISSUE TITLE
Incident summary on overview not working

### ISSUE THREAD

**Issue by Robcwilliams** [RedHatInsights/insights-frontend#276]
<img width="454" alt="screen shot 2017-10-19 at 4 02 29 pm" src="https://user-images.githubusercontent.com/343792/31791569-030773e8-b4e7-11e7-921a-424529564bdb.png">

When viewing the overview on Insights beta, this section does not display any relevant data and appears to not be working. However when clicking "view actions" on the next page it works just fine - just not on overview

**Comment by dkuc** [comment]
https://github.com/RedHatInsights/insights-frontend/pull/278

**Comment by Robcwilliams** [comment]
Resolved
