### ISSUE TITLE
Replace "Invalid Date" usage on inventory with something more descriptive

### ISSUE THREAD

**Issue by Robcwilliams** [RedHatInsights/insights-frontend#279]
<img width="397" alt="screen shot 2017-10-23 at 10 09 26 am" src="https://user-images.githubusercontent.com/343792/31895179-7d090a4a-b7de-11e7-95e0-3ede3f014a2e.png">

UI shows "Invalid Date" for a value under Last Check In. There are a few things that can cause this such as a failed initial upload or usage of --no-upload, but the term used may make it seem like there's an issue on our end like a strange date format. 

We should use something like more descriptive along the lines of "No Data Sent", "No Data Uploaded", "No Upload Received"

**Comment by Kinlaw** [comment]
@Robcwilliams is there a specific account where this is happening?

**Comment by Robcwilliams** [comment]
@Kinlaw The account it was happening on it doesn't look like those systems are there anymore. I'll probably close for now and can re-open, with account information if it happens again.
