### ISSUE TITLE
system modal bugs

### ISSUE THREAD

**Issue by jharting** [RedHatInsights/insights-frontend#289]
![screenshot_20171030_163004](https://user-images.githubusercontent.com/167352/32179469-c7475d9e-bd8f-11e7-8cc8-cf9e0cd11762.png)

(1) I am no UX expert but the unalignment of lines, boxes and the table hurts my eyes. The elements should IMHO be more aligned.

(2) Also, the system above uses display_name and neither that nor hostname is displayed anywhere

![screenshot_20171030_163034](https://user-images.githubusercontent.com/167352/32179478-cd107648-bd8f-11e7-86dd-d9a753775802.png)

(3) The hostname does not fit. Hostnames are usually long so the layout should allow for displaying all of them rather than hiding parts of it.

(4) Once at this also please change how we display name, hostname and UUID. At all times, these three pieces of information should be displayed:
* name - this is the primary way to identify a system in Insights. Either display_name or hostname value will be injected
* hostname
* uuid

Name should be the primary thing (e.g. presented as the h2 next to the system type icon). Hostname and UUID are secondary and should each have a label (current styling of UUID label+value will work for both)

**Comment by ryelo** [comment]
@jharting This isn't how it should look at all. I'll take a look at it.

**Comment by ryelo** [comment]
![default](https://user-images.githubusercontent.com/12520842/32188321-dbae75d6-bd7d-11e7-852a-c2d302213091.png)
How it should look
