### ISSUE TITLE
Font color for rule description on actions page 3 is too light to read

### ISSUE THREAD

**Issue by Kinlaw** [RedHatInsights/insights-frontend#312]
https://access.redhat.com/insightsbeta/actions/security/CVE_2017_14491_dnsmasq%7CCVE_2017_14491_ERROR?search_term=&sort_field=toString&sort_direction=ASC

![screen shot 2017-11-21 at 2 41 51 pm](https://user-images.githubusercontent.com/5181010/33093199-51316176-ceca-11e7-9ff5-3eafd1956fe5.png)

**Comment by jharting** [comment]
The same thing hapenned to planner system reboot summary

![screenshot_20171122_152122](https://user-images.githubusercontent.com/167352/33132111-ebf8171c-cf98-11e7-855c-efabe361512d.png)
