### ISSUE TITLE
Change system type mentions of "RHEV" to "RHV"

### ISSUE THREAD

**Issue by Robcwilliams** [RedHatInsights/insights-frontend#315]
Insights has a few system types for Red Hat Virtualization. When these were added the product abbreviation was "RHEV" which has since been modified to just "RHV". We will want to do the same with our labels. 

![rhv-dep1](https://user-images.githubusercontent.com/343792/33438672-868e5fb8-d5b9-11e7-8420-ac7bd0ab59b0.PNG)

**Comment by Kinlaw** [comment]
![screen shot 2017-12-12 at 1 35 21 pm](https://user-images.githubusercontent.com/5181010/33901956-736c917a-df41-11e7-988d-5203748fb982.png)
