### ISSUE TITLE
unportal minor glitches

### ISSUE THREAD

**Issue by jharting** [RedHatInsights/insights-frontend#326]
I am putting here all the minor UI glitches I found after unportal.

1) two sets of sorting indicator
![screenshot_20171218_192532](https://user-images.githubusercontent.com/167352/34121874-dc915846-e42a-11e7-9a8c-56ddaf7956a5.png)

2) Weird tab header - looks like a text that is supposed to be an al text only is shown. Should be "Playbook" only with "Ansible suported" tooltip
![screenshot_20171218_192557](https://user-images.githubusercontent.com/167352/34121875-dcb7ec72-e42a-11e7-9c60-cbb975e284f7.png)

3) System summary background overflows
![screenshot_20171218_192632](https://user-images.githubusercontent.com/167352/34121877-dcde7996-e42a-11e7-9a1b-3855bda975b2.png)

4) Severity icons should be all in one line
![screenshot_20171218_192653](https://user-images.githubusercontent.com/167352/34121878-dd06b4f6-e42a-11e7-89ff-14452a4c0cdd.png)

5) Maintenance tables have funny cell borders
![screenshot_20171218_192739](https://user-images.githubusercontent.com/167352/34121879-dd2c310e-e42a-11e7-9d16-a66668b834c3.png)

6) "Ansible supported" text in the tables - should be the logo only. Most likely the same cause as in (2)
![screenshot_20171218_192849](https://user-images.githubusercontent.com/167352/34121881-dd942bba-e42a-11e7-8b5b-3270e7c581c6.png)

7) Two system-not-checking-in bars
![screenshot_20171218_192926](https://user-images.githubusercontent.com/167352/34121882-dddbf85a-e42a-11e7-8c5c-558b81581b23.png)

8) Planner buttons are much less pretty than the rest of Insights.
![screenshot_20171218_193142](https://user-images.githubusercontent.com/167352/34121883-de18104c-e42a-11e7-8a2f-2bb7b1971c04.png)
Could for example use the same look as webhooks buttons do, which is neat!
![screenshot_20171218_193156](https://user-images.githubusercontent.com/167352/34121885-de46d2d8-e42a-11e7-9d68-b6964f921f48.png)

**Comment by ryelo** [comment]
@jharting Working on a lot of these at the moment.

**Comment by jharting** [comment]
9) Playbook cards have no columns anymore. Compare

![screenshot_20171219_161920](https://user-images.githubusercontent.com/167352/34164237-4d475032-e4d9-11e7-9b91-f74439b0743e.png)
with
![screenshot_20171219_161931](https://user-images.githubusercontent.com/167352/34164281-6c2990c8-e4d9-11e7-841a-6f9061cfad44.png)

10) Maintenance table borders still funny. The header has border all around. The body only has one border line between column names and the values. On a page with multiple tables this makes it hard to understand what systems belong to what issues.

![screenshot_20171219_162810](https://user-images.githubusercontent.com/167352/34164444-d649bde8-e4d9-11e7-9d6d-8d666893008a.png)

11) The planner buttons look great. The planner table buttons (save, cancel) could use some love also
![screenshot_20171219_162133](https://user-images.githubusercontent.com/167352/34164456-e0d42ad2-e4d9-11e7-9c4c-52b24429e64d.png)

12) On the initial page the upper-left corner spinner looks unprofessional
![screenshot_20171219_161733](https://user-images.githubusercontent.com/167352/34164526-0f41ce60-e4da-11e7-9b53-5d63a31ae0d9.png)

**Comment by ryelo** [comment]
9. I'll start on that first!
10. I think I understand that more. I'll fiddle with it and see what I can do to make it look more natural
11. Easy enough
12. There's a bug with that spinner itself, but it shouldn't be too hard

**Comment by Robcwilliams** [comment]
13. "Very Low"
![2017-12-19_17h30_58](https://user-images.githubusercontent.com/343792/34181979-6c04e58a-e4e2-11e7-9386-dcb62bc75714.png)

**Comment by ryelo** [comment]
@Robcwilliams 
13. #340

**Comment by jharting** [comment]
I merged https://github.com/RedHatInsights/insights-frontend/pull/331 with the full batch of fixes. Here are some more that either fell through the cracks or which I noticed later:

Double sorting indication (when creating new plan, etc.)
![screenshot_20171222_110817](https://user-images.githubusercontent.com/167352/34294511-272e83f2-e709-11e7-9eed-4d01c18eb41d.png)

Alert circle not aligned
![screenshot_20171222_110919](https://user-images.githubusercontent.com/167352/34294512-27511836-e709-11e7-9de8-d522e8c005af.png)

Ansible icon not aligned
![screenshot_20171222_111001](https://user-images.githubusercontent.com/167352/34294513-276fa9a4-e709-11e7-8a46-8837684cda78.png)

System modal - rule cards are touching. I guess they should not be? At least they were not touching in the past. Also, the indicent tab that's being developed also uses cards and they are separated. I am fine either way as long as we are consistent with the policies tab.
![screenshot_20171222_111233](https://user-images.githubusercontent.com/167352/34294514-278cf70c-e709-11e7-9236-cf01212d9daf.png)

**Comment by ryelo** [comment]
@jharting Working on these new bugs. I think the cards should probably take the form of the ones on the policies page, but discussion is welcome. They should be uniform, though.

**Comment by jharting** [comment]
@ryelo I agree, I like the policies-page-card-look better.

A few more glitches I found:

14. Actions page 2 - card view - severity icons should be horizontal
![screenshot_20180103_135752](https://user-images.githubusercontent.com/167352/34521504-5110d60a-f08e-11e7-939b-ab577d10ec56.png)

15. Actions page 2 - card view - if a rule group has more than 1 rule the rule-switching arrows on the sides are hidden behind the menu bar. Also, this causes the page to have a horizontal scrollbar which I don't think is the desired state.
![screenshot_20180103_135838](https://user-images.githubusercontent.com/167352/34521522-5e969328-f08e-11e7-8cf8-96d063e47dc6.png)

**Comment by ryelo** [comment]
14. ~~Sev icons should be horizontal~~ 
15. ~~Switching between cards~~ This has a fix for now (just making the arrows smaller), it might be best to revisit this and redesign switching between cards.

**Comment by Robcwilliams** [comment]
16. The "More Topics" button under Actions on the new UI isn't very prominent / does not feel like a button vs the old one

**Old**
![2018-01-03_13h46_29](https://user-images.githubusercontent.com/343792/34534541-82f41eb8-f08c-11e7-95a2-e70683163bfa.png)

**New**
![2018-01-03_13h45_54](https://user-images.githubusercontent.com/343792/34534516-6f00ca6e-f08c-11e7-825d-5b718c08278c.png)

**Comment by ryelo** [comment]
@Robcwilliams 
16. ~~More topics button~~ [#346](https://github.com/RedHatInsights/insights-frontend/pull/346)

**Comment by jharting** [comment]
@ryelo wrt **15** the small arrows look good to me. However, somehow the whole list still has weird width causing a horizontal scrollbar.

![screenshot_20180104_152648](https://user-images.githubusercontent.com/167352/34567791-f574b362-f163-11e7-8db7-c61e77c60cac.png)

**Comment by ryelo** [comment]
@jharting I think I found the problem. [#346](https://github.com/RedHatInsights/insights-frontend/pull/346)

**Comment by jharting** [comment]
Two more:
17. Default to InsightsBeta checkbox is off
![screenshot_20180105_163950](https://user-images.githubusercontent.com/167352/34616120-73d85fb4-f237-11e7-8bda-d378964b76fd.png)
18. Planner modal ui-select inputs overflow the modal
![screenshot_20180105_164022](https://user-images.githubusercontent.com/167352/34616126-77d227c6-f237-11e7-9856-1769dc6fa50c.png)

**Comment by ryelo** [comment]
17. ~~Default to InsightsBeta checkbox is off~~
18. Planner modal ui-select inputs overflow the modal

**Comment by jharting** [comment]
19. Playbook resolution modal save button blue on blue background
![screenshot_20180111_085207](https://user-images.githubusercontent.com/167352/34814671-d3fdedac-f6ae-11e7-8ccf-0ddc698427e3.png)

**Comment by ryelo** [comment]
@jharting 
19. ~~Playbook resolution save button~~ #377 
20. Announcement Formatting
21. Announcement Formatting (2)
