### ISSUE TITLE
Inventory view not showing system name

### ISSUE THREAD

**Issue by chenders1** [RedHatInsights/insights-frontend#333]
![inventory](https://user-images.githubusercontent.com/24900677/34180755-72f13ab8-e4d5-11e7-9345-be14bd15ebf2.png)

**Comment by chenders1** [comment]
Nevermind. Default sort is alphabetical and evidently those are actual hostnames.

**Comment by Robcwilliams** [comment]
Hey @chenders1 
I'm not sure if this is actually a bug vs the actual name we have recorded for this system. This issue happens on Stable & Beta but does not appear to be the system's UUID

**Comment by Robcwilliams** [comment]
=) beat me to it
