### ISSUE TITLE
Bring back # of impacted systems [Fullscreen UI]

### ISSUE THREAD

**Issue by Robcwilliams** [RedHatInsights/insights-frontend#334]
The old UI used to provide a count of the number of systems in the list below that were impacted. The new UI just provides "systems impacted" with no count

# Old UI
![2017-12-19_17h34_49](https://user-images.githubusercontent.com/343792/34182169-2576b7dc-e4e3-11e7-87da-fb2998129d81.png)

# New UI
![2017-12-19_17h35_22](https://user-images.githubusercontent.com/343792/34182199-400baf94-e4e3-11e7-9fdb-291a9197f5ac.png)

**Comment by ryelo** [comment]
@Robcwilliams I think this was fixed in @jharting's #337
