### ISSUE TITLE
Group deletion does not work in Firefox [BZ- 1527693]

### ISSUE THREAD

**Issue by Robcwilliams** [RedHatInsights/insights-frontend#336]
Copying from https://bugzilla.redhat.com/show_bug.cgi?id=1527693 which was submitted by Jaylin Zhou

**Description of problem:**
The group deletion does not work. 

**Version-Release number of selected component (if applicable):**
Current version of insightsbeta

**How reproducible:**
In the overview page of insightsbeta, click "Global filter" and the group dropdown list is displayed. Click the "delete" icon on the right side of one group name.

**Actual results:**
It changes to the view of that group.

**Expected results:**
The group should be deleted.

**Comment by jharting** [comment]
@ryelo any clue why this would be happening? It works fine in chrome but not in firefox. Although I see the icon correctly it does not react to events properly (tooltip, on-click). Even trying to inspect it in the DOM I cannot hit the icon properly, as if it had 0 width/height. Once I open the DOM and navigate to the icon the dimensions look right though. I even tried adding extra width/height, padding, z-index, etc. with no luck.
