### ISSUE TITLE
revisit esc navigation

### ISSUE THREAD

**Issue by jharting** [RedHatInsights/insights-frontend#345]
Hitting the ESC key used to bring the user back after drilling down into a more detailed view in the Insights UI. For example in the actions page one could open a category and then a specific rule after which ESC could be used to go one level higher.

This still works in some places but it's missing in others. Let's revisit this to make it consistent.

**Comment by jharting** [comment]
Firs part implemented in https://github.com/RedHatInsights/insights-frontend/pull/349

**Comment by jeudy100** [comment]
Places that don't have esc navigation:
- Policies
- Configuration
