### ISSUE TITLE
"select all systems" on actions page throws errors

### ISSUE THREAD

**Issue by jharting** [RedHatInsights/insights-frontend#414]
![screenshot_20180130_170021](https://user-images.githubusercontent.com/167352/35576393-24a15c3c-05df-11e8-884a-14eb24736ea0.png)

**Comment by jeudy100** [comment]
@jharting i couldn't reproduce this error

**Comment by jharting** [comment]
@jeudy100 

1) Open https://access.redhat.com/insightsbeta/actions/security/CVE_2017_5754_kernel%7CKERNEL_CVE_2017_5754_INTEL
2) Click "Select All" checkbox
3) The table header should change to "43 Impacted Systems  (15 Selected ..."
4) In table header click "Select All Systems"
At this point I see errors in the log

**Comment by iphands** [comment]
Yeah it breaks (shows errors) for me in the "reallySelectAll" option.

**Comment by jeudy100** [comment]
yea i was looking at the select all checkbox, sorry.
