### ISSUE TITLE
Unable to access /splash when logged in

### ISSUE THREAD

**Issue by Robcwilliams** [RedHatInsights/insights-frontend#418]
**Current State**
When I am logged into Insights, I am unable to visit the contents of /splash. When visiting /splash I am bounced back to overview. The only way for me to access the content that is available on this page is logging out of my Red Hat account and then going to the page again.

**Expected State**
Old system used to be show the splash page if not logged in when visiting /insights, if visiting /insights/ logged in bounce them to overview, however if one specifically navigated to /splash/ whether they were logged in or not, they could go and view the materials on that page

**Comment by iphands** [comment]
@Robcwilliams just an FYI

For splash stuff there is no Beta/Stable/Alpha split. Its all one thing in Drupal.
The "Needs Stable" is irrelevant.

**Comment by iphands** [comment]
@Kinlaw this is fixed over in the assets repo...
Can you review https://github.com/RedHatInsights/insights-frontend-assets/pull/3 ?

**Comment by iphands** [comment]
Merged and shipped in the assets repo
