### ISSUE TITLE
Filter dropdowns look disabled

### ISSUE THREAD

**Issue by Kinlaw** [RedHatInsights/insights-frontend#421]
The filter dropdowns are grayed out which makes them look disabled.
![screen shot 2018-02-01 at 2 39 14 pm](https://user-images.githubusercontent.com/5181010/35699396-f271f0d4-075d-11e8-8b7f-bbbda27cfbf1.png)

**Comment by ryelo** [comment]
I'm not sure about this. All the dropdowns look like that as of now where the disabled has a grey background. 
@mattnolting thoughts? Could just change the border and text to the text color

**Comment by mattnolting** [comment]
@Kinlaw you right, @ryelo we need to increeeeease contrast on the dropdown buttons.
