### ISSUE TITLE
access.redhat.com/insights/getting-started requires login

### ISSUE THREAD

**Issue by Robcwilliams** [RedHatInsights/insights-frontend#428]
We use https://access.redhat.com/insights/getting-started as a friendly URL which forwards to https://access.redhat.com/products/red-hat-insights#getstarted

Currently when accessing /insights/getting-started you are required to log into your Red Hat account prior to forwarding. The end destination, however, does not require you to log in and is available to view for anyone. 

Let's remove the login requirement when accessing /insights/getting-started and just kick them over to the forwarding page.

**Comment by iphands** [comment]
I'll catch it at the Edge (akamai)

**Comment by iphands** [comment]
```
$ curl -vk https://access.redhat.com/insights/getting-started -o /dev/null 2>&1 | fgrep location:
< location: https://access.redhat.com/products/red-hat-insights#getstarted
```
