### ISSUE TITLE
Latest Japanese translation merge request

### ISSUE THREAD

**Issue by koalakangaroo** [RedHatInsights/insights-frontend#483]
Please merge the translated Japanese version (https://translate.engineering.redhat.com/iteration/view/insights/master?dswid=5551) of /insightsbeta to master branch. 
If you are not able to download the po file, please check the attachment.

[insights_master_ja.zip](https://github.com/RedHatInsights/insights-frontend/files/2082592/insights_master_ja.zip)

**Comment by jharting** [comment]
hey @koalakangaroo, can you open a new pull request with the contents of the attachment?

**Comment by koalakangaroo** [comment]
@jharting - I tried to open a MR for this and got insufficient permission error:

~~~
# gitb
* features/ja_update
  master
# git push origin features/ja_update
ERROR: Permission to RedHatInsights/insights-frontend.git denied to koalakangaroo.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
~~~
Is something I did wrong or I really don't have the permission? I think I did this earlier and succeeded.

**Comment by jharting** [comment]
@koalakangaroo you'll need to fork a project, push the branch there and then create a pull request https://help.github.com/articles/creating-a-pull-request/
