### ISSUE TITLE
Auto resizing of inventory cuts off group options in drop down list

### ISSUE THREAD

**Issue by Robcwilliams** [RedHatInsights/insights-frontend#90]
Steps to replicate:

1. Go to inventory - account 540155
2. Global filters are set to default or all systems, view that there are many groups with names starting with A to T
3. Select group "Shifty". The content box will resize due to 3 systems
4. Attempt to access the global filters again. Options in the drop down stop at R, unable to access 5 other groups after that listing

![irepbj6ncy](https://cloud.githubusercontent.com/assets/343792/26000589/876f82d8-36f7-11e7-9104-22f157b828de.gif)

**Comment by mattnolting** [comment]
Issue is a result of a portal chrome styling setting '.page-wrap' z-index to 1 and causing the footer to hide an overlapping page content. Issue is resolved by unsetting z-index.

**Comment by iphands** [comment]
Closed from PR #140
