### ISSUE TITLE
Can we just hide the goalLite extra stuffs while it loads?

### ISSUE THREAD

**Issue by iphands** [RedHatInsights/insights-frontend#93]
Currently we see the UI below.
I think it would look better with either a much more compact loading spinner, or just ng-if away those boxes until they are loaded.

![tmp](https://cloud.githubusercontent.com/assets/129737/26158495/091276d8-3aea-11e7-8efb-d551fee5b500.jpg)

**Comment by iphands** [comment]
Maybe something like this?

![tmp2](https://cloud.githubusercontent.com/assets/129737/26158735/9e1d1792-3aea-11e7-87a9-8773f768e406.jpg)

**Comment by ryelo** [comment]
<img width="433" alt="screen shot 2017-07-05 at 1 21 37 pm" src="https://user-images.githubusercontent.com/12520842/27876389-ec1e6e6c-6184-11e7-8d5c-d6c5beb077f0.png">
How's this look?

**Comment by iphands** [comment]
Looks great
