### ISSUE TITLE
Executive reports missing days worth of "Action Trends" data

### ISSUE THREAD

**Issue by Robcwilliams** [RedHatInsights/insights-frontend#97]
Data from May 11th to May 20th appears to not render in most Action Trend graphs

<img width="938" alt="screen shot 2017-05-23 at 10 56 12 am" src="https://cloud.githubusercontent.com/assets/343792/26360803/167f5cde-3fa7-11e7-9954-9a410b70594d.png">
<img width="936" alt="screen shot 2017-05-23 at 10 59 38 am" src="https://cloud.githubusercontent.com/assets/343792/26360819/1d90d73c-3fa7-11e7-8150-7c3ab076defe.png">

**Comment by iphands** [comment]
I dont this is a front end bug
